services:
  postgres:
    image: postgres:16-alpine
    container_name: school-db
    environment:
      POSTGRES_USER: school_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: school_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: